version: '3'
services:
  web:
    image: nginx:1.13.5-alpine
    ports:
      - 80:80
    restart: unless-stopped
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - www:/var/www/html
    depends_on:
      - php
  php:
    build: ./php
    restart: unless-stopped
    volumes:
      - www:/var/www/html:rw
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    env_file:
      - env
    ports:
      - 3306:3306
    command: ["--character-set-server=utf8", "--collation-server=utf8_general_ci"]
    volumes:
      - mysql:/var/lib/mysql:rw
  installation:
    build: ./installation
    env_file:
      - env
    volumes:
      - ./installation_data:/installation_data:rw
      - www:/var/www/html:rw
volumes:
  www:
  mysql:
